version: "3"

services:

  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /home/www/nginx/html:/usr/share/nginx/html
      - /home/www/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/www/nginx/conf/conf.d:/etc/nginx/conf.d
      - /home/www/nginx/log:/var/log/nginx
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/www/mysql/conf:/etc/mysql
      - /home/www/mysql/db:/var/lib/mysql
  redis:
    image: redis:6.0.19
    ports:
      - 6379:6379
    volumes:
      - /home/www/redis/redis.conf:/etc/redis/redis.conf
      - /home/www/redis/data:/data
  pblog:
    image: pblog:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 8888:8888
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis
      - nginx
