server:
  servlet:
    # 应用的访问路径
    context-path: /rulin

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: rulinblog
  profiles:
    active: dev